version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    command: --innodb_use_native_aio=0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./db_schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass